# Generated by Django 2.2.1 on 2019-05-16 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190516_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='main_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='main_account', to='api.Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_account', to='api.Account'),
        ),
    ]
